name: Build Kernel

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Set up Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y ccache libssl-dev flex bison clang lld lldb curl

      - name: Download and Extract Clang
        run: |
          mkdir clang && cd clang
          wget https://android.googlesource.com/platform//prebuilts/clang/host/linux-x86/+archive/refs/heads/main/clang-r522817.tar.gz
          tar xf clang-r522817.tar.gz
          rm clang-r522817.tar.gz
          cd ..

      - name: Set Environment Variables
        run: |
          echo "KBUILD_BUILD_HOST=DV-WORK" >> $GITHUB_ENV
          echo "KBUILD_BUILD_USER=picasso09" >> $GITHUB_ENV
          echo "PATH=$(pwd)/clang/bin:$PATH" >> $GITHUB_ENV

      - name: Build Kernel
        run: |
          make -j$(nproc --all) O=out ARCH=arm64 oppo6765_defconfig
          make -j$(nproc --all) ARCH=arm64 O=out \
                                HOSTCC="ccache clang" \
                                HOSTCXX="ccache clang++" \
                                CC="ccache clang" \
                                LD=ld.lld \
                                AR=llvm-ar \
                                NM=llvm-nm \
                                OBJCOPY=llvm-objcopy \
                                OBJDUMP=llvm-objdump \
                                READELF=llvm-readelf \
                                OBJSIZE=llvm-size \
                                STRIP=llvm-strip \
                                CROSS_COMPILE=aarch64-linux-gnu- \
                                CROSS_COMPILE_ARM32=arm-linux-gnueabi-

      - name: Upload Image.gz-dtb Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Image.gz-dtb
          path: out/arch/arm64/boot/Image.gz-dtb
